name: vcl
# author: Aliaksei Liulis <lai@tut.by>
description: Dart implementation of vcl interface C++Builder, Delphi.
version: 1.2.0
homepage: https://github.com/ds-42/dart-vcl

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies:
  sprintf: ^6.0.0