name: form
description: Create vcl form
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  lints: ^1.0.0

dependencies:
  vcl:
    path: ../../
